# see https://github.com/karlicoss/pymplate for up-to-date reference

name: CI
on:
  push:
    branches: '*'
    tags: 'v[0-9]+.*' # only trigger on 'release' tags for PyPi
    # Ideally I would put this in the pypi job... but github syntax doesn't allow for regexes there :shrug:
    # P.S. fuck made up yaml DSLs.
    # TODO cron?
  workflow_dispatch: # needed to trigger workflows manually

env:
  # useful for scripts & sometimes tests to know
  CI: true

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        python-version: [3.6, 3.7, 3.8]

    runs-on: ${{ matrix.platform }}

    steps:
    # ugh https://github.com/actions/toolkit/blob/main/docs/commands.md#path-manipulation
    - run: echo "$HOME/.local/bin" >> $GITHUB_PATH

    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - uses: actions/checkout@v2
      with:
        submodules: recursive

    # uncomment for SSH debugging
    # - uses: mxschmitt/action-tmate@v2

    - run: .ci/run

    - uses: actions/upload-artifact@v2
      with:
        name: .coverage.mypy 
        path: .coverage.mypy/
      # restrict to a single python version, otherwise uploading fails
      if: ${{ matrix.python-version == '3.8' }}
